# Generated by Django 4.2.1 on 2023-06-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
