# Generated by Django 4.2.1 on 2023-06-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_completed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='dueDate',
        ),
    ]
